


ACCOUNT.TYPE.STANDARD   = 1
ACCOUNT.TYPE.TAX.EXEMPT = 2

FIFO.TAX.LOTS = 1  # FIFO
LIFO.TAX.LOTS = 2  # LIFO
AWC.TAX.LOTS  = 3 # Average Weighted Cost

STRATEGY.ID = "Test"

DEFAULT.ACCOUNT.NAME = "TestAccount01"
INITIAL.BUDGET.VALUE = 100000
DEFAULT.CURRENCY = "RUB"

DIRECTION.BUY = 1
DIRECTION.SELL = -1

SLICE.T0 = 0
SLICE.T1 = 1
SLICE.T2 = 2

DEFAULT.ACCOUNT.TYPE = #ACCOUNT.TYPE.STANDARD 
  ACCOUNT.TYPE.TAX.EXEMPT
DEFAULT.TAX.LOT.ACCOUNTING = FIFO.TAX.LOTS

DEFAULT.TAX.RATE = 0.13
DEFAULT.INITIAL.MARGIN = 0.3

DEFAULT.MARKET.SPREAD = 0.002
BROKER.COMMISSION = T
EXCHANGE.COMMISSION = T

SHORT.MARGINAL.RATE = 0.14
LONG.MARGINAL.RATE = 0.16